baseURL: https://eens-en.netlify.app
title: "Extra Ecclesiam Nulla Salus"

module:
   imports:
      - path: github.com/eens1/config

languageName: "English"
defaultContentLanguage: en
params:
   dateFormat: "Jan 02, 2006"
menu:
   main:
      - name: Home
        url: /
        weight: 1

      - name: Contact
        url: /contact
        weight: 2

      - name: "About"
        url: /about
        weight: 3 

      - name: "Fran√ßais"
        url: "https://eens-fr.netlify.app"
        weight: 4 

      - name: "Italiano"
        url: "https://eens-it.netlify.app"
        weight: 5 
params:
  featuredPosts:
    - /spirituality/rosary
