module:
   imports:
      - path: github.com/eens1/config

languageName: "English"
defaultContentLanguage: en
params:
   dateFormat: "Jan 02, 2006"
menu:
   main:
      - identifier: home
        url: /
        weight: 1
        pre: <i class="fas fa-home"></i>

      - name: Bible
        url: /bible
        weight: 2

      - name: Doctrine
        url: /doctrine
        weight: 3

      - name: Spirituality
        url: /spirituality
        weight: 4

      - identifier: apologetics
        name: Apologetics 
        url: /apologetics
        weight: 5

      - url: /contact
        weight: 6
        name: Contact

      - identifier: lang
        weight: 7
        name: "LANG"
        pre: "<i class='fas fa-globe'></i>"

      - url: https://eens-fr.netlify.app
        name: Fran√ßais
        parent: lang

      - url: https://eens-it.netlify.app
        name: Italiano 
        parent: lang

params:
  featuredPosts:
    - /spirituality/rosary
